cmake_minimum_required(VERSION 3.24)

if(NOT EXISTS "${BENCHMARK}" OR NOT IS_DIRECTORY "${SOURCE_DIR}")
    message(FATAL_ERROR "A full application and source working directory are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT_DIR}")

# 固定夹具不含逗号或分号；这里只验证受控字段，不实现通用 CSV 框架
function(read_csv path)
    file(STRINGS "${path}" rows ENCODING UTF-8)
    list(POP_FRONT rows header_line)
    string(REPLACE "," ";" header "${header_line}")
    list(LENGTH header width)
    set(unique_header "${header}")
    list(REMOVE_DUPLICATES unique_header)
    list(LENGTH unique_header unique_width)
    if(NOT width EQUAL unique_width)
        message(FATAL_ERROR "Duplicate CSV fields: ${path}")
    endif()
    if(NOT rows)
        message(FATAL_ERROR "Empty CSV: ${path}")
    endif()
    foreach(row IN LISTS rows)
        string(REPLACE "," ";" values "${row}")
        list(LENGTH values row_width)
        if(NOT row_width EQUAL width)
            message(FATAL_ERROR "CSV width mismatch: ${path}")
        endif()
    endforeach()
    set(CSV_HEADER "${header}" PARENT_SCOPE)
    set(CSV_ROWS "${rows}" PARENT_SCOPE)
endfunction()

function(value_of row field output)
    list(FIND CSV_HEADER "${field}" index)
    if(index LESS 0)
        message(FATAL_ERROR "Missing CSV field: ${field}")
    endif()
    string(REPLACE "," ";" values "${row}")
    list(GET values ${index} value)
    set(${output} "${value}" PARENT_SCOPE)
endfunction()

function(expect_all field expected)
    foreach(row IN LISTS CSV_ROWS)
        value_of("${row}" "${field}" actual)
        if(NOT actual STREQUAL "${expected}")
            message(FATAL_ERROR "${field}: expected ${expected}, got ${actual}")
        endif()
    endforeach()
endfunction()

function(run_case name profile)
    execute_process(
        COMMAND "${BENCHMARK}" --benchmark --algorithm dod --profile "${profile}"
            --pass-warmups 0 --pass-repeats 1 --pass-targets 1
            --csv "${OUTPUT_DIR}/${name}.csv" ${ARGN}
        WORKING_DIRECTORY "${SOURCE_DIR}"
        RESULT_VARIABLE result
        OUTPUT_FILE "${OUTPUT_DIR}/${name}.log"
        ERROR_FILE "${OUTPUT_DIR}/${name}.error.log"
        TIMEOUT 90)
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "${name} failed: ${result}; see ${OUTPUT_DIR}")
    endif()
endfunction()

run_case(default smoke)
run_case(explicit smoke
    --merge-score-min-parallel-entries 256 --split-score-min-parallel-entries 256
    --mesh-min-parallel-triangles 256)
read_csv("${OUTPUT_DIR}/default.csv")
expect_all(experimentSchemaVersion 4)
expect_all(mergeScoreMinParallelEntryCount 256)
expect_all(splitScoreMinParallelEntryCount 256)
expect_all(meshEmitMinParallelTriangleCount 256)
set(default_rows "${CSV_ROWS}")
read_csv("${OUTPUT_DIR}/explicit.csv")
list(LENGTH default_rows default_count)
list(LENGTH CSV_ROWS explicit_count)
if(NOT default_count EQUAL explicit_count)
    message(FATAL_ERROR "Default row count changed")
endif()
math(EXPR last_row "${default_count} - 1")
foreach(index RANGE ${last_row})
    list(GET default_rows ${index} left)
    list(GET CSV_ROWS ${index} right)
    foreach(field normalizedMeshHash topologyHash activeLeafHash activeTriangleCount replayInputHash
            pass_mergeScoreEffectiveAction pass_splitScoreEffectiveAction pass_meshEmitEffectiveAction)
        value_of("${left}" "${field}" left_value)
        value_of("${right}" "${field}" right_value)
        if(NOT left_value STREQUAL right_value)
            message(FATAL_ERROR "Default versus explicit mismatch: row ${index}, ${field}")
        endif()
    endforeach()
endforeach()

# 此配置内部会重复选取四个预设，所有输出行都必须保留下限覆盖
run_case(presets pass-policy-replay
    --merge-score-min-parallel-entries 0 --split-score-min-parallel-entries 255
    --mesh-min-parallel-triangles 257 --pass-policy parallel)
read_csv("${OUTPUT_DIR}/presets.csv")
expect_all(experimentSchemaVersion 4)
expect_all(mergeScoreMinParallelEntryCount 0)
expect_all(splitScoreMinParallelEntryCount 255)
expect_all(meshEmitMinParallelTriangleCount 257)
list(LENGTH CSV_ROWS preset_rows)
if(NOT preset_rows EQUAL 24)
    message(FATAL_ERROR "Expected four six-frame preset replays")
endif()

foreach(profile pass-crossover-replay pass-crossover-stress-replay)
    run_case("${profile}" "${profile}"
        --merge-score-min-parallel-entries 0 --split-score-min-parallel-entries 255
        --mesh-min-parallel-triangles 257)
    read_csv("${OUTPUT_DIR}/${profile}.csv")
    expect_all(schemaVersion 2)
    expect_all(mergeScoreMinParallelEntryCount 0)
    expect_all(splitScoreMinParallelEntryCount 255)
    expect_all(meshEmitMinParallelTriangleCount 257)
    expect_all(equivalent 1)
    expect_all(correct 1)
    list(LENGTH CSV_ROWS pair_rows)
    if(NOT pair_rows EQUAL 11)
        message(FATAL_ERROR "Expected 11 paired strategy records")
    endif()

    # 实际阶段也必须继承配置；只看新 CSV 列不足以排除“写对了却没用到”
    run_case("${profile}-zero" "${profile}"
        --merge-score-min-parallel-entries 0 --split-score-min-parallel-entries 0
        --mesh-min-parallel-triangles 0)
    read_csv("${OUTPUT_DIR}/${profile}-zero.csv")
    set(zero_rows "${CSV_ROWS}")
    run_case("${profile}-high" "${profile}"
        --merge-score-min-parallel-entries 999999999 --split-score-min-parallel-entries 999999999
        --mesh-min-parallel-triangles 999999999)
    read_csv("${OUTPUT_DIR}/${profile}-high.csv")
    expect_all(equivalent 1)
    expect_all(correct 1)
    list(LENGTH CSV_ROWS high_count)
    list(LENGTH zero_rows zero_count)
    if(NOT high_count EQUAL 11 OR NOT zero_count EQUAL 11)
        message(FATAL_ERROR "Paired configuration record count changed")
    endif()
    set(covered_passes "")
    foreach(index RANGE 10)
        list(GET zero_rows ${index} low)
        list(GET CSV_ROWS ${index} high)
        foreach(field passId requestedAction frozenStateId resultHash)
            value_of("${low}" "${field}" low_value)
            value_of("${high}" "${field}" high_value)
            if(NOT low_value STREQUAL high_value)
                message(FATAL_ERROR "Minimum changed paired input/result: ${profile}, ${field}")
            endif()
        endforeach()
        value_of("${low}" passId pass)
        value_of("${low}" requestedAction action)
        if((pass STREQUAL "mergeScore" OR pass STREQUAL "splitScore" OR pass STREQUAL "meshEmit")
                AND action MATCHES "^parallel")
            value_of("${low}" effectiveWorkers low_workers)
            value_of("${high}" effectiveWorkers high_workers)
            if(NOT low_workers GREATER 1 OR NOT high_workers EQUAL 1)
                message(FATAL_ERROR "Minimum not consumed by paired phase: ${profile}, ${pass}")
            endif()
            list(APPEND covered_passes "${pass}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES covered_passes)
    list(LENGTH covered_passes covered_count)
    if(NOT covered_count EQUAL 3)
        message(FATAL_ERROR "Missing paired CPU phase coverage: ${profile}")
    endif()
endforeach()

# 独立新路径避免旧成功文件掩盖错误分支；不删除测试目录或历史结果
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef run_id)
set(case_index 0)
foreach(invalid IN ITEMS --merge-score-min-parallel-entries --split-score-min-parallel-entries
        --mesh-min-parallel-triangles --profile)
    math(EXPR case_index "${case_index} + 1")
    set(csv "${OUTPUT_DIR}/invalid-${run_id}-${case_index}.csv")
    set(value -1)
    if(invalid STREQUAL "--profile")
        set(value pass-crossover-formal)
    endif()
    execute_process(
        COMMAND "${BENCHMARK}" --benchmark --csv "${csv}" "${invalid}" "${value}"
        WORKING_DIRECTORY "${SOURCE_DIR}"
        RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET TIMEOUT 10)
    if(result STREQUAL "0" OR EXISTS "${csv}")
        message(FATAL_ERROR "Invalid CLI must fail before writing CSV: ${invalid}")
    endif()
endforeach()
message(STATUS "Benchmark policy/CSV integration passed")
