#ifndef PARALLEL_ROAM_CBT_DEBUG_VISUALIZATION_SHARED_H
#define PARALLEL_ROAM_CBT_DEBUG_VISUALIZATION_SHARED_H

// 保留来源的深度与 split/merge 配色；只使用宏，以便 HLSL 直接包含
#define ROAM_DEBUG_ORIGINAL_RED 0.28
#define ROAM_DEBUG_ORIGINAL_GREEN 0.34
#define ROAM_DEBUG_ORIGINAL_BLUE 0.30
#define ROAM_DEBUG_SUBDIVIDED_LOW_RED 0.08
#define ROAM_DEBUG_SUBDIVIDED_LOW_GREEN 0.72
#define ROAM_DEBUG_SUBDIVIDED_LOW_BLUE 0.62
#define ROAM_DEBUG_SUBDIVIDED_HIGH_RED 0.10
#define ROAM_DEBUG_SUBDIVIDED_HIGH_GREEN 0.34
#define ROAM_DEBUG_SUBDIVIDED_HIGH_BLUE 0.95
#define ROAM_DEBUG_ORIGINAL_HIGHLIGHT 0.35
#define ROAM_DEBUG_SUBDIVIDED_HIGHLIGHT 0.70
#define ROAM_DEBUG_EVENT_HIGHLIGHT 1.00

#define ROAM_DEBUG_SPLIT_RED 0.95
#define ROAM_DEBUG_SPLIT_GREEN 0.08
#define ROAM_DEBUG_SPLIT_BLUE 0.06

#define ROAM_DEBUG_MERGE_RED 0.10
#define ROAM_DEBUG_MERGE_GREEN 0.88
#define ROAM_DEBUG_MERGE_BLUE 0.18

#endif
