include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/TracyVersion.cmake")

function(parallel_roam_verify_tracy_source source)
    # 解包目录没有 Git 元数据，核验实际客户端、构建脚本与许可内容
    file(GLOB_RECURSE public_files LIST_DIRECTORIES false RELATIVE "${source}" "${source}/public/*")
    file(GLOB cmake_files LIST_DIRECTORIES false RELATIVE "${source}" "${source}/cmake/*.cmake")
    set(files ${public_files} ${cmake_files} CMakeLists.txt LICENSE)
    list(SORT files)
    set(manifest "")
    foreach(path IN LISTS files)
        if(NOT EXISTS "${source}/${path}")
            message(FATAL_ERROR "Incomplete Tracy source: ${path}")
        endif()
        file(SHA256 "${source}/${path}" checksum)
        string(APPEND manifest "${path}=${checksum}\n")
    endforeach()
    string(SHA256 tree_hash "${manifest}")
    if(NOT tree_hash STREQUAL PARALLEL_ROAM_TRACY_CLIENT_TREE_SHA256)
        message(FATAL_ERROR "Tracy client source differs from pinned v${PARALLEL_ROAM_TRACY_VERSION}: ${tree_hash}")
    endif()
endfunction()

function(parallel_roam_prepare_profiling)
    add_library(parallel_roam_profiling_options INTERFACE)
    if(PARALLEL_ROAM_PROFILE_SYMBOLS)
        if(MSVC)
            target_compile_options(parallel_roam_profiling_options INTERFACE /Zi)
            target_link_options(parallel_roam_profiling_options INTERFACE /DEBUG)
        else()
            target_compile_options(parallel_roam_profiling_options INTERFACE -g)
        endif()
    endif()
    if(PARALLEL_ROAM_PROFILE_FRAME_POINTERS)
        if(MSVC)
            target_compile_options(parallel_roam_profiling_options INTERFACE /Oy-)
        else()
            target_compile_options(parallel_roam_profiling_options INTERFACE -fno-omit-frame-pointer)
        endif()
    endif()
    if(NOT PARALLEL_ROAM_ENABLE_TRACY)
        return()
    endif()

    set(tracy_source "${PARALLEL_ROAM_TRACY_SOURCE_DIR}")
    if(NOT tracy_source AND PARALLEL_ROAM_FETCH_MISSING_DEPS)
        include(FetchContent)
        FetchContent_Declare(parallel_roam_tracy
            URL "${PARALLEL_ROAM_TRACY_ARCHIVE_URL}"
            URL_HASH "SHA256=${PARALLEL_ROAM_TRACY_ARCHIVE_SHA256}"
            DOWNLOAD_EXTRACT_TIMESTAMP true
            SOURCE_SUBDIR unused)
        FetchContent_MakeAvailable(parallel_roam_tracy)
        set(tracy_source "${parallel_roam_tracy_SOURCE_DIR}")
    endif()
    if(NOT tracy_source)
        message(FATAL_ERROR "Set PARALLEL_ROAM_TRACY_SOURCE_DIR to pinned v${PARALLEL_ROAM_TRACY_VERSION}, or explicitly enable dependency fetching.")
    endif()
    parallel_roam_verify_tracy_source("${tracy_source}")
    # 统一整个进程的客户端选项，禁止混入另一份已配置的 TracyClient
    if(TARGET TracyClient OR TARGET Tracy::TracyClient)
        message(FATAL_ERROR "Tracy client must be owned by the project profiling configuration.")
    endif()
    foreach(flag TRACY_ENABLE TRACY_ON_DEMAND TRACY_ONLY_LOCALHOST TRACY_ONLY_IPV4
            TRACY_NO_BROADCAST TRACY_NO_CALLSTACK TRACY_NO_CONTEXT_SWITCH TRACY_NO_SAMPLING
            TRACY_NO_WAIT_STACKS TRACY_NO_VSYNC_CAPTURE TRACY_NO_FRAME_IMAGE
            TRACY_NO_SYSTEM_TRACING TRACY_NO_CRASH_HANDLER TRACY_STATIC)
        set(${flag} ON)
    endforeach()
    foreach(flag TRACY_NO_EXIT TRACY_MANUAL_LIFETIME TRACY_LTO TRACY_Fortran)
        set(${flag} OFF)
    endforeach()
    add_subdirectory("${tracy_source}" "${CMAKE_BINARY_DIR}/profiling/tracy" EXCLUDE_FROM_ALL)
    add_library(parallel_roam_cpu_profiling STATIC "${PROJECT_SOURCE_DIR}/src/profiling/CpuProfiling.cpp")
    target_include_directories(parallel_roam_cpu_profiling PRIVATE "${PROJECT_SOURCE_DIR}/src")
    target_compile_features(parallel_roam_cpu_profiling PRIVATE cxx_std_20)
    target_link_libraries(parallel_roam_cpu_profiling PUBLIC Tracy::TracyClient)
    target_link_libraries(parallel_roam_profiling_options INTERFACE parallel_roam_cpu_profiling)
endfunction()
